tap 'homebrew/bundle'
tap 'oven-sh/bun'

brew 'zsh' # Zsh shell
brew 'git' # Git 
brew 'stow' # Stow dotfiles manager
brew 'neovim' # Neovim text editor
brew 'tmux' # Tmux terminal multiplexer

# Terminal tools
brew 'starship' # Starship shell prompt
brew 'eza' # Better ls command
brew 'bat' # Better cat command
brew 'lazygit' # Terminal Git GUI
brew 'gitmoji' # Gitmoji commit messages
brew 'oven-sh/bun/bun' # Another node replacement
brew 'zoxide' # Smarter cd command
brew 'fnm' # Node version manager

# Shell tools
brew 'zsh-autosuggestions' # Zsh autosuggestions
brew 'zsh-syntax-highlighting' # Zsh syntax highlighting
brew 'zsh-completions' # Zsh completions